#!/bin/bash

echo "🔄 TuZi Chat 插件重新安装指南"
echo "================================="
echo ""

echo "⚠️  由于配置文件更新，需要重新安装插件"
echo ""

echo "📋 重新安装步骤："
echo ""
echo "1️⃣ 卸载旧版本："
echo "   - 打开 PopClip 偏好设置"
echo "   - 找到 'TuZi Chat' 插件"
echo "   - 右键点击或点击删除按钮"
echo "   - 确认卸载"
echo ""

echo "2️⃣ 安装新版本："
echo "   - 双击 'TuZiChat.popclipext' 文件夹"
echo "   - 点击 'Install Extension' 按钮"
echo "   - 如果提示未签署，选择信任并安装"
echo ""

echo "3️⃣ 配置插件（现在应该有设置按钮了）："
echo "   - 打开 PopClip 偏好设置"
echo "   - 找到 'TuZi Chat' 插件"
echo "   - 点击右侧的 ⚙️ 设置按钮"
echo ""

echo "4️⃣ 必需配置："
echo "   📌 API Key: sk-BxyGGul3LKvGBVbnSCDa9F61Y9gy8RPFHu2nCaRxzM7oZGqj"
echo "   📌 Model: claude-sonnet-4-20250514 (Claude 4 Sonnet 推荐)"
echo "   📌 Response Handling: Copy (推荐)"
echo ""

echo "5️⃣ 可选配置："
echo "   - System Message: 保持默认或自定义"
echo "   - Reset Timer: 15 分钟"
echo "   - Show Reset Button: 启用"
echo ""

echo "6️⃣ 测试插件："
echo "   - 在任意文本编辑器中输入: 'Hello, how are you?'"
echo "   - 选中这段文本"
echo "   - 查看 PopClip 菜单是否出现 'Chat' 按钮"
echo "   - 点击 'Chat' 按钮测试"
echo ""

echo "🎯 修复内容："
echo "✅ 在 Config.json 中定义了 options（配置选项）"
echo "✅ 简化了 JavaScript 文件结构"
echo "✅ 修复了设置按钮不显示的问题"
echo "✅ 保持了所有原有功能"
echo ""

echo "💡 如果仍然没有设置按钮："
echo "   1. 确保完全卸载了旧版本"
echo "   2. 重启 PopClip 应用"
echo "   3. 重新安装插件"
echo ""

echo "🆘 需要帮助？"
echo "   如果问题仍然存在，请提供："
echo "   - PopClip 偏好设置中插件列表的截图"
echo "   - 控制台应用中的错误日志" 