#!/bin/bash

echo "🧪 TuZi Chat PopClip 插件功能测试"
echo "================================="
echo ""

echo "📋 测试步骤："
echo "1. 在任意文本编辑器中输入: 'Hello, how are you?'"
echo "2. 选中这段文本"
echo "3. 查看 PopClip 菜单是否出现"
echo "4. 检查是否有 'Chat' 按钮"
echo "5. 点击 'Chat' 按钮"
echo ""

echo "🔍 如果插件不能点击，请检查："
echo ""
echo "✅ 插件是否启用："
echo "   - 打开 PopClip 偏好设置"
echo "   - 确认 'TuZi Chat' 有勾选标记"
echo ""
echo "✅ API Key 是否配置："
echo "   - 点击 TuZi Chat 的设置按钮 ⚙️"
echo "   - 确认 API Key 字段不为空"
echo "   - 应该填入: sk-BxyGGul3LKvGBVbnSCDa9F61Y9gy8RPFHu2nCaRxzM7oZGqj"
echo ""
echo "✅ 模型是否选择："
echo "   - 确认 Model 选择了: claude-sonnet-4-20250514"
echo ""
echo "✅ 文本是否正确选中："
echo "   - 确保选中的是文本，不是图片或其他内容"
echo "   - 选中的文本长度应该 > 0"
echo ""

echo "🚨 常见问题："
echo ""
echo "❌ 如果按钮显示为灰色："
echo "   → 检查 API Key 是否正确配置"
echo "   → 检查网络连接是否正常"
echo ""
echo "❌ 如果没有 Chat 按钮："
echo "   → 检查插件是否启用"
echo "   → 重启 PopClip 应用"
echo ""
echo "❌ 如果点击没有反应："
echo "   → 检查选中的文本是否有效"
echo "   → 查看 PopClip 日志获取错误信息"
echo ""

echo "🔧 调试方法："
echo "1. 打开 '控制台' 应用"
echo "2. 搜索 'PopClip'"
echo "3. 查看错误日志"
echo ""

echo "📞 如果问题仍然存在，请提供："
echo "   - 插件在偏好设置中的状态截图"
echo "   - 选中文本时 PopClip 菜单的截图"
echo "   - 控制台中的错误信息" 